- CMakeLists.txt
- README.md
- dtmerge/CMakeLists.txt
- dtmerge/README.md
- dtmerge/dtmerge.1
- dtmerge/dtmerge.c
- dtmerge/dtoverlay.c
- dtmerge/dtoverlay.h
- otpset/CMakeLists.txt
- overlaycheck/CMakeLists.txt
- overlaycheck/README.md
- overlaycheck/overlaycheck
- overlaycheck/overlaycheck_exclusions.txt
- ovmerge/CMakeLists.txt
- ovmerge/README.md
- raspinfo/CMakeLists.txt
As a way to make it possible for third parties to run checks on overlays before submission, publish the `overlaycheck` utility along with its dependency dtmerge (also found in the userland repo). Use CMake for easy installation, and add READMEs for each utility.
> Add overlaycheck and dependency

- dtmerge/CMakeLists.txt
- otpset/CMakeLists.txt
- overlaycheck/CMakeLists.txt
- ovmerge/CMakeLists.txt
- raspinfo/CMakeLists.txt
- vclog/CMakeLists.txt
Currently, dtmerge.1 gets installed into /usr/{local}/man/. The global path for manpages should be /usr/**share**/man.
This PR fixes that and also uses GNUInstallDirs for everything else. Functionally it should make no difference, but if shared objects get added later, it will save some headache when packaging everything.
> CMake: Use GNUInstallDirs

- vclog/vcdbg.c
```
vcdbg.c: In function ‘find_hdr_requested_log’:
vcdbg.c:576:10: warning: ‘val’ may be used uninitialized [-Wmaybe-uninitialized]
576 |   return correct_to_be_in_virtual_loc(toc, val);
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vcdbg.c:555:12: note: ‘val’ was declared here
555 |   uint32_t val;
|            ^~~
vcdbg.c: In function ‘main’:
vcdbg.c:356:9: warning: ‘header_current_msg’ may be used uninitialized [-Wmaybe-uninitialized]
356 |         memcpy_vc_memory(start_circular_buff + offset_of_current_read_pos,
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
357 |                          buffer_start + offset_of_current_read_pos,
|                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
358 |                          left_in_buffer);
| …
```
> vclog: Fix uninitialised variables warning

- ovmerge/ovmerge
Perl can be configured at build time to support 64-bit integers - ivsize=8 - even on 32-bit platforms. The Raspberry Pi Perl builds are configured this way but some aren't, causing interpreter errors on the 64-bit mask value 0xffffffffffffffff. Replacing this with a -1 has no negative effect when ivsize=8, and it allows the tool to run when ivsize=4 (without supporting values > 32-bit).
See: #23
> ovmerge: Allow it to run on 32-bit Perls

- vclog/vcdbg.c
Reported by HiassofT
vclog -m is dying with a bus error on RPi4 / LE master since we updated glibc to 2.37. glibc switched to simd optimized memcpy
https://sourceware.org/git/?p=glibc.git;a=commit;h=e6f3fe362f1aab78b1448d69ecdbd9e3872636d3 and for whatever reason it doesn't seem to be happy with the 128bit access to the 64bit aligned address from your mmap'ed memory region - is that maybe iomem? (D_q is a define for q3, src a define for x1
Program received signal SIGBUS, Bus error.
__memcpy_generic () at ../sysdeps/aarch64/multiarch/../memcpy.S:155 155		ldr	D_q, [src]
(gdb) where
dest@entry=0x7fadcd4014 "\305\300 \001", src=0x7fadd54168 "",
src@entry=0x7fadd54164 "\305\300 \001", n=<optimized out>, n@entry=376444)
at /home/hias/libreelec/libreelec-master/build.LibreELEC-RPi4.aarch64-12.0-d …
> vcdbg: Increase boundary to work with newer glibc

- pinctrl/pinctrl-completion.bash
If the last word on the line doesn't have a trailing space then it should still be considered for completion. Be careful to avoid looking at the final element in COMP_WORDS to ensure that happens.
> pinctrl: completion: Careful with the current word

- README.md
- dtmerge/CMakeLists.txt
- dtmerge/README.md
- dtmerge/dtoverlay-post
- dtmerge/dtoverlay-pre
- dtmerge/dtoverlay.1
- dtmerge/dtoverlay.2
- dtmerge/dtoverlay.c
- dtmerge/dtoverlay.h
- dtmerge/dtoverlay_main.c
- dtmerge/dtparam.1
- dtmerge/utils.c
- dtmerge/utils.h
These utilities previously lived in the soon-to-be-abandoned userland repo. While adding them here the shared-library status of libdtovl has been dropped for simplicity.
> Add dtoverlay and dtparam from the userland repo

- CMakeLists.txt
- dtmerge/CMakeLists.txt
- otpset/CMakeLists.txt
- overlaycheck/CMakeLists.txt
- ovmerge/CMakeLists.txt
- pinctrl/CMakeLists.txt
- raspinfo/CMakeLists.txt
- vcgencmd/CMakeLists.txt
- vclog/CMakeLists.txt
- vcmailbox/CMakeLists.txt
Using this future proofs the build and surpresses a harmless but annoying warning:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
...
```
> CMakeLists.txt: use min...max notation

- dtmerge/dtmerge.c
- dtmerge/dtoverlay.c
- dtmerge/dtoverlay.h
- dtmerge/dtoverlay_main.c
- dtmerge/utils.c
Some more recent features in the overlay handling cause problems when applying overlays at runtime. Fragments that target other fragments, and the ability to embed label references into parameters/overrides, both add the ability to copy phandles around. Phandles that represent unresolved symbols require fixups (literally `__fixups__`), so when one of these phandles is copied or overwritten then the fixups also have to be updated. Failure to do so results in kernel complaints about invalid phandles, or parameters appearing not to do anything.
This PR adds logic to track the movement of phandles. It is not completely foolproof - writing a string over a phandle won't be spotted, for example - but it should work in sensible use cases.
See: https://github.com/raspberrypi/linux/issues/5652
> Fix the fixups

- eeptools/eepdump.c
Compilation fails with GCC 13:
https://github.com/openwrt/openwrt/commit/e57eb9f28e7ba383796df8cae1b3ca39804f6326?w=1#commitcomment-137339982
```
FAILED: eeptools/eepdump
: && /home/cschuette/openwrt/snapshot/openwrt/staging_dir/toolchain-aarch64_cortex-a72_gcc-13.2.0_musl/bin/aarch64-openwrt-linux-musl-gcc -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -ffile-prefix-map=/home/cschuette/openwrt/snapshot/openwrt/build_dir/target-aarch64_cortex-a72_musl/bcm27xx-utils-2024-01-15=bcm27xx-utils-2024-01-15 -ffunction-sections -fdata-sections -flto=auto -fno-fat-lto-objects -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Wall -Wextra -Werror -DNDEBUG -L/home/cschuette/openwrt/snapshot/openwrt/staging_dir/toolchain-aarch64_cortex-a72_gcc-13.2.0_ …
```
> eeptools: eepdump: init type before calling eepio_atom_start

- raspinfo/raspinfo
You can configure the kernel to require root to access dmesg.
Lets use sudo anyway - we already do in other places in this script
> raspinfo: Add sudo to dmesg

- eeptools/eepmake.c
- pinctrl/gpiochip_rp1.c
Use the atomic set/clr feature of RP1 to set the output drive on a GPIO, which makes it much faster.
See: https://github.com/raspberrypi/utils/issues/73
> pinctrl: Speed up RP1 GPIO drive set

- pinctrl/pinctrl.c
GPIO argument is required, not optional
> Correct help-text for pinctrl poll

- raspinfo/raspinfo
By expanding the board-identification regex
Fixes #72
> raspinfo: Display EEPROM info for Pi 400, CM4, CM4S and Pi 5

- pinctrl/pinctrl.c
To be able to redirect stdout 'pinctrl' output in polling mode, a flush stdout after every level change is needed.
> flush stdout on every level change

- vclog/vclog.c
Fixes:
./vclog/vclog.c:199:30: error: 'msg.size' may be used uninitialized [-Werror=maybe-uninitialized]
199 |             payload_len = msg.size - sizeof(msg_hdr_t);
|                           ~~~^~~~~
./vclog/vclog.c:193:23: note: 'msg' declared here
193 |             msg_hdr_t msg;
|                       ^~~
> vclog: fix compiler error with gcc-14.1

- pinctrl/pinctrl-completion.bash
Lintian warns using a shebang in a bash-completion script. While I don't think they do any particular harm, it is redundant.
Incidentally, the reason I was looking into this was for including raspi-utils in Ubuntu. During this process, the build initially broke on `dh_missing` warning that the completions weren't being included in the final built package. Might be worth adding the following lines to `debian/raspi-utils-core.install`:
```
usr/share/bash-completion/completions/pinctrl
usr/share/bash-completion/completions/vcgencmd
```
> Fix lintian warning about bash-completion shebangs

- vcgencmd/vcgencmd.1
- vcmailbox/raspirev.7
- vcmailbox/vcmailbox.7
Since groff 1.23, lintian warns that table macros (`TS`, `TE`) are included without certain settings, which generated by the [tbl(1)](https://manpages.debian.org/bookworm/groff-base/tbl.1.en.html) pre-processor. Include a header indicating that the tbl(1) pre-processor should be run for all files that include tables.
> Fix modern groff warnings in manpages

- CMakeLists.txt
- README.md
- kdtc/CMakeLists.txt
- kdtc/README.md
- kdtc/kdtc
kdtc is a wrapper around the "dtc" Device Tree compiler that resolves any #includes and macros, running the source file through cpp.
When run without any dtc options, it attempts to detect the input format and do the right thing.
> Add kdtc - a "kernel" dts compiler

- ovmerge/ovmerge
I noticed that the fragment numbering in the overlay is not updated when the renumbering is done.
E.g. Suppose you have a `fragment@23 ...` as fragment and a `something = "+23"` in the overlay section. The `ovmerge` will assign a new number to the fragment (for example 7) but the `something` configuration is still on `"+23"`. This patch corrects the situation, thus the overlay will be merged as `something = "+7"`.
cf. https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/configuration/device-tree.adoc#overlayfragment-parameters
> ovmerge: Aligns the numbering of overlay param values to renumbered fragments.

- piolib/examples/dpi_csync.c
Was not initializing correct output pin in interlaced mode
> piolib: examples: dpi_csync: Bug fix

- piolib/examples/apitest.c
- piolib/include/rp1_pio_if.h
- piolib/pio_rp1.c
In many places, the number of bytes in a data transfer is stored as a 32-bit (or greater) value, but the ioctl API to the kernel stores it in a 16-bit field, alongside which is a 16-bit gap due to the alignment requirements of the pointer that follows.
Increase the size of data_bytes to a uint32_t, so that it can handle larger transfers. Since using different sizes as either end can lead to unpredictable results, a separate IOCTL is used for larger transfers, allowing the kernel support to be determined and backwards compatibility to be maintained.
See: https://github.com/raspberrypi/utils/issues/107
> piolib: Increase data_bytes range to 32-bits

- piolib/examples/quadrature_encoder.pio.h
Fixes compile error:
```
In function 'quadrature_encoder_get_count',
inlined from 'main' at /build/bcm2835-utils/piolib/examples/quadrature_encoder.c:58:21:
/build/bcm2835-utils/piolib/examples/quadrature_encoder.pio.h:106:12: error: 'ret' may be used uninitialized [-Werror=maybe-uninitialized]
106 |     return ret;
|            ^~~
```
> piolib: fixes may be used uninitialized

- piolib/examples/apitest.c
- piolib/pio_rp1.c
rp1_pio_sm_config_xfer and rp1_pio_sm_xfer_data both return either 1 or
0, despite not being declared as returning a bool. This is due to copy/
paste errors - they should simply return the int return value of the
underlying ioctl.
Fixes: https://github.com/raspberrypi/utils/issues/112
Also extend apitest to catch this.
> piolib: Correct transfer return values

- piolib/include/rp1_pio_if.h
- piolib/pio_rp1.c
Similar to the increase in supported transfer lengths, for performance reasons it may be helpful to allow larger DMA buffers. This requires an updated rp1-pio driver that supports the new ioctl messages, otherwise calls to pio_sm_config_xfer with buffer sizes of 65536 or larger will fail.
> piolib: Support larger DMA buffers

- eeptools/eepdump.c
- eeptools/eeplib.c
- eeptools/eeplib.h
- eeptools/eepmake.c
- eeptools/eeprom_settings.txt
The POWER_SUPPLY atom describes the ability of the HAT to supply power to the Pi. This is declared in the EEPROM settings text file using the current_supply property. The default value for current_supply is zero, and unless a non-zero value is provided then the POWER_SUPPLY atom is omitted from the EEPROM image.
> eeptools: Add the POWER_SUPPLY atom

- pinctrl/CMakeLists.txt
- pinctrl/gpiochip.h
- pinctrl/gpiochip_bcm2712.c
- pinctrl/gpiochip_bcm2835.c
- pinctrl/gpiolib.c
- pinctrl/library_gpiochips.c
- pinctrl/util.h
Create the gpiolib library to contain all of the gpiolib code and the gpiochips, so that applications such as pinctrl are just linked against it, and not all of the individual object files. The named section approach to collecting the gpiochips does not work in this situation, so add an explicit array of pointers to the gpiochip implementations.
> pinctrl: Create and use gpiolib library

- kdtc/README.md
Add some more usage examples to the README, mainly copied from a Forums post.
See: https://forums.raspberrypi.com/viewtopic.php?t=377084
> kdtc: Expand the README

- README.md
- dtmerge/CMakeLists.txt
- dtmerge/README.md
- pinctrl/CMakeLists.txt
- pinctrl/README.md
- piolib/CMakeLists.txt
- piolib/README.md
Previously the subprojects with libraries as targets build them as static (.a) libraries. Add the option of building them as shared libraries by making use of the standard BUILD_SHARED_LIBS option.
This is a simpler version of https://github.com/raspberrypi/utils/pull/128, which was a useful prod.
> Optionally build shared libraries

- eeptools/README.md
Did the kernel change device enumeration?
With `-a=0x50`:
```sh
This will attempt to talk to an eeprom at i2c address 0x0x50. Make sure there is an eeprom at this address.
This script comes with ABSOLUTELY no warranty. Continue only if you know what you are doing.
Do you wish to continue? (yes/no): yes
./eeptools/eepflash.sh: 161: echo: echo: I/O error
Writing...
dd: failed to open '/sys/class/i2c-dev/i2c-9/device/9-000x50/eeprom': No such file or directory
Closing EEPROM Device.
./eeptools/eepflash.sh: 189: echo: echo: I/O error
Error doing I/O operation.
```
With `-a=50`:
```sh
This will attempt to talk to an eeprom at i2c address 0x50. Make sure there is an eeprom at this address.
This script comes with ABSOLUTELY no warranty. Continue only if you know what you are doing.
Do you wish …
```
> eeptools: Fix flash example
